package com.example.accommodationmicroservice.event;

public enum EventType {

    DELETE_USER_STARTED, DELETE_ACCOMMODATION_STARTED, DELETE_ACCOMMODATION_FAILED, DELETE_SLOT_FAILED,
    ACCOMMODATION_DELETED, SLOTS_DELETED, ACCOMMODATION_CREATED, ACCOMMODATION_CREATE_FAILED, RATE_CREATED,

    RATE_CHANGED, RATE_DELETED, RATE_CREATE_FAILED
}
